# This file is part of Mamba
# Copyright (c) 2013 - Oscar Campos <oscar.campos@member.fsf.org>

"""
.. module:: mamba_services
    :platform: Unix, Windows
    :synopsis: This file is needed for mamba-admin command tools

.. moduleauthor:: Oscar Campos <oscar.campos@member.fsf.org>
.. warning:
    Please, do not edit this file, the Mamba command line tools (mamba-admin)
    need this file as is
"""

import sys
sys.path.append('.')

from mamba.utils import config
